[package]
name = "mbootd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mboot-protocol = { path = "../mboot-protocol", features = ["std"] }
x11rb = { version = "0.14.0", default-features = false, features = ["composite", "xtest"] }
sha2 = { version = "0.10.9", default-features = false }
